version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: posts_api_db
    environment:
      POSTGRES_DB: fiap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - posts_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Node.js
  app:
    build: .
    container_name: posts_api_app
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fiap
      DB_USER: postgres
      DB_PASSWORD: root
      JWT_SECRET: f6b0947563fca52b04d9aa8c5e31c542e87bb7f54fd74164ebdc24615e8eee73dc69d5f4aca1a8d147899df9f6b95ae07b4b78018c932140c0db105bac00d124
      BCRYPT_ROUNDS: 12
      LOG_LEVEL: info
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - posts_api_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  posts_api_network:
    driver: bridge 